name: ensembler
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.19.*
  - matplotlib=3.3.*
  - pandas=1.2.*
  - imgaug=0.4.*
  - albumentations=0.5.*
  - scikit-learn=0.24.*
  - ffmpeg==4.3.*
  - pip
  - pip:
    - -r requirements.txt
