name: ensembler
channels:
  - pytorch
  - conda-forge
  - r
dependencies:
  - python=3.8
  - numpy=1.19.*
  - matplotlib=3.3.*
  - pandas=1.2.*
  - pytorch=1.8.*
  - torchvision=0.9.*
  - cudatoolkit=11.1
  - imgaug=0.4.*
  - albumentations=0.5.*
  - scikit-learn=0.24.*
  - pytorch-lightning=1.2.*
  - ffmpeg=4.3.*
  - pip
  - ir-kernel
  - r-tidyverse
  - pip:
    - -r requirements.txt
