name: ensembler
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.19.*
  - matplotlib=3.3.*
  - pandas=1.2.*
  - pytorch=1.8.*
  - torchvision=0.9.*
  - cudatoolkit=10.1
  - imgaug=0.4.*
  - albumentations=0.5.*
  - scikit-learn=0.24.*
  - pytorch-lightning=1.2.*
  - pip
  - pip:
    - https://github.com/qubvel/segmentation_models.pytorch/archive/refs/tags/v0.1.3.tar.gz
    - p_tqdm==1.3.*
    - flake8==3.8.*
    - yapf==0.30.*
    - pytest==6.2.*
    - pytest-cov==2.11.*
